/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./src/components/AboutSection.vue')['default']
    ContactSection: typeof import('./src/components/ContactSection.vue')['default']
    PersonalProjects: typeof import('./src/components/PersonalProjects.vue')['default']
    ProjectSection: typeof import('./src/components/ProjectSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillSection: typeof import('./src/components/SkillSection.vue')['default']
    WorkProjectSection: typeof import('./src/components/WorkProjectSection.vue')['default']
  }
}
